name: Build Native Libraries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# FIXME: disabling macOS currently for vpx no decoder problem
# FIXME: disabling windows currently for 

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            arch: x86_64
          - os: windows-latest
            shell: 'msys2 {0}'
            arch: x86_64
          # - os: macos-latest
          #   shell: bash
          #   arch: arm64
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v2
        
      - name: Print number of CPU cores
        run: |
          echo "Number of CPU cores: ${{ steps.cpu-cores.outputs.count }}"
 
      - name: Prepare Environment for checking (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false

      - name: Check base paths (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export BASE=$SOURCES_DIR
          export DEST=$BASE/ffmpeg-build-windows

          echo "SOURCES_DIR=$SOURCES_DIR"
          echo "BASE=$BASE"
          echo "DEST=$DEST"

          # force make failure
          # forcefully-making-failure-here

      - name: Prepare Environment (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-libunistring
            mingw-w64-x86_64-perl
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-aom
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-make
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-tools-git
            mingw-w64-x86_64-doxygen
            binutils
            diffutils
            grep
            make
            zip
            wget
            tar
            git   

      - name: Prepare Environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc make cmake zip \
            yasm nasm \
            pkg-config \
            mingw-w64

      - name: Prepare Environment (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install \
            gcc make cmake zip \
            vorbis-tools \
            yasm nasm \
            pkg-config \
            mingw-w64

          brew install automake fdk-aac git lame libass libtool libvorbis libvpx \
            opus sdl shtool texi2html theora wget x264 x265 xvid nasm

      - name: Check gcc, strings and ar (Windows)
        if: matrix.os == 'windows-latest'
        shell: 'msys2 {0}'
        run: |
          which x86_64-w64-mingw32-gcc
          x86_64-w64-mingw32-gcc --version

          # ls /mingw64/bin/ | grep strings
          # ls /mingw64/bin/ | grep ar

          # FIXME: not found
          # x86_64-w64-mingw32-strings --version
          # x86_64-w64-mingw32-ar --version
          # x86_64-w64-mingw32-strip --version
          # x86_64-w64-mingw32-nm --version

          # WORKAROUND (copy strings.exe as x86_64-w64-mingw32-strings.exe)
          cp /mingw64/bin/strings.exe /mingw64/bin/x86_64-w64-mingw32-strings.exe
          cp /mingw64/bin/ar.exe /mingw64/bin/x86_64-w64-mingw32-ar.exe
          cp /mingw64/bin/strip.exe /mingw64/bin/x86_64-w64-mingw32-strip.exe
          cp /mingw64/bin/nm.exe /mingw64/bin/x86_64-w64-mingw32-nm.exe

          x86_64-w64-mingw32-strings --version
          x86_64-w64-mingw32-ar --version
          x86_64-w64-mingw32-strip --version
          x86_64-w64-mingw32-nm --version
            
      - name: Download and extract dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: 'msys2 {0}'
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          mkdir -p $SOURCES_DIR
          cd $SOURCES_DIR
          
          # Core repositories
          git clone --branch n4.2 --depth 1 https://github.com/FFmpeg/FFmpeg.git
          git clone --branch v1.8.1 --depth 1 https://chromium.googlesource.com/webm/libvpx
          git clone --depth 1 https://github.com/mirror/x264.git
          git clone --branch 3.1.1 --depth 1 https://github.com/videolan/x265.git
          git clone --branch v1.0.0-errata1 --depth 1 https://aomedia.googlesource.com/aom
          git clone --branch v2.0.0 --depth 1 https://github.com/cisco/openh264.git

          # Archive downloads
          wget ${WGET_OPTIONS} http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
          tar xzf libogg-1.3.4.tar.gz
          rm libogg-1.3.4.tar.gz

          wget ${WGET_OPTIONS} http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.3.tar.gz
          tar xzf libvorbis-1.3.3.tar.gz
          rm libvorbis-1.3.3.tar.gz

          wget ${WGET_OPTIONS} https://ftp.osuosl.org/pub/xiph/releases/opus/opus-1.3.1.tar.gz
          tar xzf opus-1.3.1.tar.gz
          rm opus-1.3.1.tar.gz

          wget ${WGET_OPTIONS} https://netcologne.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar xzf lame-3.100.tar.gz
          rm lame-3.100.tar.gz
        env:
          WGET_OPTIONS: ${{ matrix.os == 'windows-latest' && '--no-check-certificate' || '' }}

      - name: Download and extract dependencies (Linux and MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          mkdir -p $SOURCES_DIR
          cd $SOURCES_DIR
          
          # Core repositories
          git clone --branch n4.2 --depth 1 https://github.com/FFmpeg/FFmpeg.git
          git clone --branch v1.8.1 --depth 1 https://chromium.googlesource.com/webm/libvpx
          git clone --depth 1 https://github.com/mirror/x264.git
          git clone --branch 3.1.1 --depth 1 https://github.com/videolan/x265.git
          git clone --branch v1.0.0-errata1 --depth 1 https://aomedia.googlesource.com/aom
          git clone --branch v2.0.0 --depth 1 https://github.com/cisco/openh264.git

          # Archive downloads
          wget ${WGET_OPTIONS} http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
          tar xzf libogg-1.3.4.tar.gz
          rm libogg-1.3.4.tar.gz

          wget ${WGET_OPTIONS} http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.3.tar.gz
          tar xzf libvorbis-1.3.3.tar.gz
          rm libvorbis-1.3.3.tar.gz

          wget ${WGET_OPTIONS} https://ftp.osuosl.org/pub/xiph/releases/opus/opus-1.3.1.tar.gz
          tar xzf opus-1.3.1.tar.gz
          rm opus-1.3.1.tar.gz

          wget ${WGET_OPTIONS} https://netcologne.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar xzf lame-3.100.tar.gz
          rm lame-3.100.tar.gz

      - name: Apply patch for libavcodec/x86/mathops.h
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          mkdir -p $SOURCES_DIR
          cd $SOURCES_DIR/FFmpeg

          # create patch file
          PATCH_FILE=patches/libavcodec_x86_mathops.h.patch

          # check exists
          if [ ! -f $PATCH_FILE ]; then
            echo "Patch file not found: $PATCH_FILE"
            exit 1
          fi

          # check exists libavcodec/x86/mathops.h
          if [ ! -f libavcodec/x86/mathops.h ]; then
            echo "$PWD/libavcodec/x86/mathops.h not found"
            exit 1
          fi

          # apply patch
          patch -p1 < $PATCH_FILE
          rm -f $PATCH_FILE

      - name: Build Libraries (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        env:
          FREE_CONFIG: "--disable-all --enable-libvorbis --enable-libvpx --enable-libaom --enable-libopus --enable-libmp3lame --enable-decoder=vp8,vp9,libaom_av1,libopus,libmp3lame --enable-encoder=libvpx_vp8,libvpx_vp9,libaom_av1,libopus,libmp3lame --enable-muxer=ogg,webm,matroska,liblamemp3 --enable-demuxer=ogg,webm,matroska --enable-bsf=vp9_superframe"
          FULL_CONFIG: "--enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libvorbis --enable-libaom --enable-libopenh264 --enable-libopus --enable-libmp3lame"
          COMMON_CONFIG: "--disable-static --enable-shared --disable-doc --enable-pic --disable-programs --disable-postproc --disable-avdevice --enable-version3 --enable-avcodec --enable-avformat --enable-avfilter --enable-swscale --enable-swresample --pkg-config-flags=--static --pkg-config=pkg-config"
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export NCORES=${{ steps.cpu-cores.outputs.count }}
          export BASE=$WORKSPACE_DIR
          export DEST=$BASE/ffmpeg-build-windows
          export PREFIX="--prefix=$DEST"
          export HOST="--host=x86_64-w64-mingw32"
          export CROSSPREFIX="--cross-prefix=x86_64-w64-mingw32-"
          export PKG_CONFIG_PATH=$DEST/lib/pkgconfig

          cd $SOURCES_DIR/libogg-1.3.4
          ./configure $PREFIX $HOST --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../libvorbis-1.3.3
          ./configure $PREFIX $HOST --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../opus-1.3.1
          ./configure $PREFIX $HOST --disable-shared --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install
          
          cd ../lame-3.100
          ./configure $PREFIX $HOST --disable-shared --disable-frontend --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install

          mkdir -p vpx-build-windows
          cd vpx-build-windows
          CROSS=x86_64-w64-mingw32- ../../libvpx/configure --target=x86_64-win64-gcc $PREFIX \
            --enable-static --disable-shared --disable-debug --enable-experimental --enable-static-msvcrt \
            --disable-examples --disable-tools --disable-docs --disable-unit-tests \
            --enable-pic --enable-small
          make -j $NCORES && make install

          cd ../

          cd ../x264
          ./configure $HOST $PREFIX $CROSSPREFIX --disable-cli --enable-static --enable-strip --enable-pic \
            --disable-lavf --disable-swscale
          make -j $NCORES && make install

          cd ../x265/build/linux
          echo "SET(CMAKE_SYSTEM_NAME Windows)" >> build.cmake
          echo "SET(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc) " >> build.cmake
          echo "SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++) " >> build.cmake
          echo "SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres) " >> build.cmake
          echo "SET(CMAKE_RANLIB x86_64-w64-mingw32-ranlib) " >> build.cmake
          echo "SET(CMAKE_ASM_YASM_COMPILER yasm) " >> build.cmake
          echo "option(ENABLE_SHARED OFF) " >> build.cmake
          cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST -DENABLE_SHARED=off \
            -DCMAKE_TOOLCHAIN_FILE=build.cmake ../../source
          make -j $NCORES && make install

          cd $SOURCES_DIR/
          cd ./aom/build
          cmake -G "Unix Makefiles" -DENABLE_TESTS=0 -DENABLE_DOCS=0 -DCMAKE_INSTALL_PREFIX=$DEST \
            -DCMAKE_TOOLCHAIN_FILE=$SOURCES_DIR/aom/build/cmake/toolchains/x86_64-mingw-gcc.cmake ..
          make -j $NCORES && make install

          cd ../../openh264
          make -j $NCORES OS=mingw_nt ARCH=x86_64 PREFIX=$DEST install

          export WINDOWS_CONFIG="--arch=x86_64 --target-os=mingw32 $CROSSPREFIX $PREFIX --disable-dxva2 --disable-w32threads"

          mkdir -p $BASE/release/windows64/free
          cd ../FFmpeg
          ./configure $FREE_CONFIG $COMMON_CONFIG $WINDOWS_CONFIG \
            --extra-cflags="-I$DEST/include -static -static-libstdc++" \
            --extra-ldflags="-L$DEST/lib -static -static-libstdc++"
          make -j $NCORES && make install
          cp $DEST/bin/*.dll $BASE/release/windows64/free/

          mkdir -p $BASE/release/windows64/full
          cd ../FFmpeg
          make clean
          ./configure $FULL_CONFIG $COMMON_CONFIG $WINDOWS_CONFIG \
            --extra-cflags="-I$DEST/include -static-libstdc++ -static-libgcc -static" \
            --extra-cxxflags="-I$DEST/include -static-libstdc++ -static-libgcc -static" \
            --extra-ldflags="-L$DEST/lib -static-libstdc++ -static-libgcc -static"
          make -j $NCORES && make install
          cp $DEST/bin/*.dll $BASE/release/windows64/full/
          cp /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/libgcc_s_seh-1.dll $BASE/release/windows64/full/

      - name: Build Libraries (MacOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        env:
          FREE_CONFIG: "--disable-all --enable-libvorbis --enable-libvpx --enable-libaom --enable-libopus --enable-libmp3lame --enable-decoder=vp8,vp9,libaom_av1,libopus,libmp3lame --enable-encoder=libvpx_vp8,libvpx_vp9,libaom_av1,libopus,libmp3lame --enable-muxer=ogg,webm,matroska,liblamemp3 --enable-demuxer=ogg,webm,matroska --enable-bsf=vp9_superframe"
          FULL_CONFIG: "--enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libvorbis --enable-libaom --enable-libopenh264 --enable-libopus --enable-libmp3lame"
          COMMON_CONFIG: "--disable-static --enable-shared --disable-doc --enable-pic --disable-programs --disable-postproc --disable-avdevice --enable-version3 --enable-avcodec --enable-avformat --enable-avfilter --enable-swscale --enable-swresample --pkg-config-flags=--static --pkg-config=pkg-config"
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export NCORES=${{ steps.cpu-cores.outputs.count }}
          export BASE=$WORKSPACE_DIR
          export DEST=$BASE/ffmpeg-build-macos
          export PREFIX="--prefix=$DEST"
          export PKG_CONFIG_PATH=$DEST/lib/pkgconfig
          export ARCH=${{ matrix.arch }}
          export MACOS_CONFIG="--arch=$ARCH --extra-cflags=-I$DEST/include --extra-ldflags=-L$DEST/lib $PREFIX"
          
          cd $SOURCES_DIR/libogg-1.3.4
          ./configure $PREFIX --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../libvorbis-1.3.3
          ./configure $PREFIX --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../opus-1.3.1
          ./configure $PREFIX --disable-shared --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install
          
          cd ../lame-3.100
          ./configure $PREFIX --disable-shared --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install
          
          # WORKAROUND: skipping libvpx build in order to avoid `no decoder found` error
          # mkdir -p vpx-build-macos
          # cd vpx-build-macos
          # # ../../libvpx/configure $PREFIX \
          # #   --enable-static --disable-shared --disable-debug --enable-experimental \
          # #   --disable-examples --disable-tools --disable-docs --disable-unit-tests \
          # #   --enable-pic --enable-small --target=$ARCH-darwin-gcc
          # ../../libvpx/configure $PREFIX \
          #   --enable-static --disable-shared --disable-debug --enable-experimental \
          #   --disable-examples --disable-tools --disable-docs --disable-unit-tests \
          #   --enable-pic --enable-small
          # make -j $NCORES && make install
          # cd ../
          
          cd ../x264
          ./configure $PREFIX --disable-cli --enable-static --enable-pic --enable-strip --disable-lavf --disable-swscale
          make -j $NCORES && make install
          
          cd ../x265/build/linux
          cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST -DENABLE_SHARED=off \
            -DCMAKE_SYSTEM_PROCESSOR=$ARCH ../../source
          make -j $NCORES && make install
          
          cd ../../../aom/build
          cmake -G "Unix Makefiles" -DENABLE_TESTS=0 -DENABLE_DOCS=0 -DCMAKE_INSTALL_PREFIX=$DEST \
            -DCMAKE_SYSTEM_PROCESSOR=$ARCH ..
          make -j $NCORES && make install
          
          cd ../../openh264
          make -j $NCORES OS=darwin ARCH=$ARCH PREFIX=$DEST install
          
          mkdir -p $BASE/release/darwin-$ARCH/free
          cd $SOURCES_DIR/FFmpeg
          ./configure $FREE_CONFIG $COMMON_CONFIG $MACOS_CONFIG
          make -j $NCORES && make install
          cd $DEST/lib && cp lib*.dylib $BASE/release/darwin-$ARCH/free/
          
          mkdir -p $BASE/release/darwin-$ARCH/full
          cd $SOURCES_DIR/FFmpeg
          make clean
          ./configure $FULL_CONFIG $COMMON_CONFIG $MACOS_CONFIG --extra-libs=-lpthread
          make -j $NCORES && make install
          cd $DEST/lib && cp lib*.dylib $BASE/release/darwin-$ARCH/full/

      - name: Build Libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        env:
          FREE_CONFIG: "--disable-all --enable-libvorbis --enable-libvpx --enable-libaom --enable-libopus --enable-libmp3lame --enable-decoder=vp8,vp9,libaom_av1,libopus,libmp3lame --enable-encoder=libvpx_vp8,libvpx_vp9,libaom_av1,libopus,libmp3lame --enable-muxer=ogg,webm,matroska,liblamemp3 --enable-demuxer=ogg,webm,matroska --enable-bsf=vp9_superframe"
          FULL_CONFIG: "--enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libvorbis --enable-libaom --enable-libopenh264 --enable-libopus --enable-libmp3lame"
          COMMON_CONFIG: "--disable-static --enable-shared --disable-doc --enable-pic --disable-programs --disable-postproc --disable-avdevice --enable-version3 --enable-avcodec --enable-avformat --enable-avfilter --enable-swscale --enable-swresample --pkg-config-flags=--static --pkg-config=pkg-config"
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export NCORES=${{ steps.cpu-cores.outputs.count }}
          export ARCH=${{ matrix.arch }}
          export BASE=$WORKSPACE_DIR
          export DEST=$BASE/ffmpeg-build-linux
          export PREFIX="--prefix=$DEST"
          export PKG_CONFIG_PATH=$DEST/lib/pkgconfig
          export LINUX_CONFIG="--extra-cflags=-I$DEST/include --extra-ldflags=-L$DEST/lib $PREFIX"
          
          cd $SOURCES_DIR/libogg-1.3.4
          ./configure $PREFIX --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../libvorbis-1.3.3
          ./configure $PREFIX --disable-shared --enable-static && make -j $NCORES && make install
          
          cd ../opus-1.3.1
          ./configure $PREFIX --disable-shared --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install
          
          cd ../lame-3.100
          ./configure $PREFIX --disable-shared --enable-static CFLAGS="-O3 -fPIC" && make -j $NCORES && make install
          
          mkdir -p vpx-build-linux
          cd vpx-build-linux
          ../../libvpx/configure $PREFIX \
            --enable-static --disable-shared --disable-debug --enable-experimental \
            --disable-examples --disable-tools --disable-docs --disable-unit-tests \
            --enable-pic --enable-small
          make -j $NCORES && make install

          cd ../
          
          cd ../x264
          ./configure $PREFIX --disable-cli --enable-static --enable-pic --enable-strip --disable-lavf --disable-swscale
          make -j $NCORES && make install
          
          cd ../x265/build/linux
          cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST -DENABLE_SHARED=off ../../source
          make -j $NCORES && make install
          
          cd ../../../aom/build
          cmake -G "Unix Makefiles" -DENABLE_TESTS=0 -DENABLE_DOCS=0 -DCMAKE_INSTALL_PREFIX=$DEST ..
          make -j $NCORES && make install
          
          cd ../../openh264
          make -j $NCORES OS=linux ARCH=$ARCH PREFIX=$DEST install
          
          mkdir -p $BASE/release/linux64/free
          cd $SOURCES_DIR
          cd ./FFmpeg
          ./configure $FREE_CONFIG $COMMON_CONFIG $LINUX_CONFIG
          make -j $NCORES && make install
          cd $DEST/lib && cp lib*.so* $BASE/release/linux64/free
          
          mkdir -p $BASE/release/linux64/full
          cd $SOURCES_DIR
          cd ./FFmpeg
          make clean
          ./configure $FULL_CONFIG $COMMON_CONFIG $LINUX_CONFIG --extra-libs=-lpthread
          make -j $NCORES && make install
          cd $DEST/lib && cp lib*.so* $BASE/release/linux64/full

      - name: Copy Native Libraries to Project Structure (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export BASE=$WORKSPACE_DIR

          # Create directories for free version
          mkdir -p natives-free/velvet-video-natives/windows64
          
          # Create directories for full version  
          mkdir -p natives-full/velvet-video-natives/windows64
          
          # Copy built libraries for free version
          cp -r $BASE/release/windows64/free/* natives-free/velvet-video-natives/windows64/
          
          # Copy built libraries for full version
          cp -r $BASE/release/windows64/full/* natives-full/velvet-video-natives/windows64/
          
          # Copy source files
          mkdir -p natives-free/src
          mkdir -p natives-full/src
          # But not actually copy the source files, because they are too big
          # cp -r $SOURCES_DIR/* natives-free/src/
          # cp -r $SOURCES_DIR/* natives-full/src/

      - name: Copy Native Libraries to Project Structure (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export BASE=$WORKSPACE_DIR

          # Create directories for free version
          mkdir -p natives-free/velvet-video-natives/linux64
          
          # Create directories for full version  
          mkdir -p natives-full/velvet-video-natives/linux64
          
          # Copy built libraries for free version
          cp -r $BASE/release/linux64/free/* natives-free/velvet-video-natives/linux64/
          
          # Copy built libraries for full version
          cp -r $BASE/release/linux64/full/* natives-full/velvet-video-natives/linux64/
          
          # Copy source files
          mkdir -p natives-free/src
          mkdir -p natives-full/src
          # But not actually copy the source files, because they are too big
          # cp -r $SOURCES_DIR/* natives-free/src/
          # cp -r $SOURCES_DIR/* natives-full/src/

      - name: Copy Native Libraries to Project Structure (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          export WORKSPACE_DIR=$PWD
          export SOURCES_DIR=$WORKSPACE_DIR/build-sources
          export ARCH=${{ matrix.arch }}
          export BASE=$WORKSPACE_DIR

          # Create directories for free version
          mkdir -p natives-free/velvet-video-natives/macos-$ARCH

          # Create directories for full version
          mkdir -p natives-full/velvet-video-natives/macos-$ARCH

          # Copy built libraries for free version
          cp -r $BASE/release/darwin-$ARCH/free/* natives-free/velvet-video-natives/macos-$ARCH/

          # Copy built libraries for full version
          cp -r $BASE/release/darwin-$ARCH/full/* natives-full/velvet-video-natives/macos-$ARCH/

          # Copy source files
          mkdir -p natives-free/src
          mkdir -p natives-full/src

          # But not actually copy the source files, because they are too big
          # cp -r $SOURCES_DIR/* natives-free/src/
          # cp -r $SOURCES_DIR/* natives-full/src/

      # - name: Clean up unnecessary files
      #   run: |
      #     # Clean up natives-free directories
      #     rm -rf natives-free/src/aom/.git natives-free/src/aom/examples natives-free/src/aom/test natives-free/src/aom/tools
      #     rm -rf natives-free/src/FFmpeg/.git natives-free/src/FFmpeg/doc natives-free/src/FFmpeg/tests natives-free/src/FFmpeg/tools
      #     rm -rf natives-free/src/FFmpeg/presets natives-free/src/FFmpeg/libpostproc natives-free/src/FFmpeg/libavdevice
      #     rm -rf natives-free/src/FFmpeg/libavcodec/mips
      #     rm -rf natives-free/src/libvpx/.git natives-free/src/libvpx/examples natives-free/src/libvpx/test natives-free/src/libvpx/tools
      #     rm -rf natives-free/src/openh264 natives-free/src/x264 natives-free/src/x265

      #     # Clean up natives-full directories
      #     rm -rf natives-full/src/aom/.git natives-full/src/aom/examples natives-full/src/aom/test natives-full/src/aom/tools
      #     rm -rf natives-full/src/FFmpeg/.git natives-full/src/FFmpeg/doc natives-full/src/FFmpeg/tests natives-full/src/FFmpeg/tools
      #     rm -rf natives-full/src/FFmpeg/presets natives-full/src/FFmpeg/libpostproc natives-full/src/FFmpeg/libavdevice
      #     rm -rf natives-full/src/FFmpeg/libavcodec/mips
      #     rm -rf natives-full/src/libvpx/.git natives-full/src/libvpx/examples natives-full/src/libvpx/test natives-full/src/libvpx/tools
      #     rm -rf natives-full/src/openh264/.git natives-full/src/openh264/docs natives-full/src/openh264/test
      #     rm -rf natives-full/src/openh264/testbin natives-full/src/openh264/autotest natives-full/src/openh264/res
      #     rm -rf natives-full/src/x264/.git natives-full/src/x264/doc natives-full/src/x264/tools
      #     rm -rf natives-full/src/x265/.git natives-full/src/x265/doc natives-full/src/x265/source/profile natives-full/src/x265/source/test

      - name: Zip for Artifacts
        run: |
          zip -r natives-free.zip natives-free
          zip -r natives-full.zip natives-full
          
      - name: Upload Artifacts (free)
        uses: actions/upload-artifact@v3
        with:
          name: native-libs-${{ matrix.os }}-${{ matrix.arch }}
          path: natives-free.zip

      - name: Upload Artifacts (full)
        uses: actions/upload-artifact@v3
        with:
          name: native-libs-${{ matrix.os }}-${{ matrix.arch }}
          path: natives-full.zip

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Build with Gradle
        shell: bash
        run: ./gradlew clean jar --no-daemon

      - name: Upload Artifacts (from Gradle)
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            natives-free/build/libs/*.jar
            natives-full/build/libs/*.jar

